queue:
  name: Hosted macOS
  demands: msbuild

variables:
  BuildConfiguration: 'Release'

steps:

- task: MSBuild@1
  displayName: 'Build project CameraPrevew'
  inputs:
    solution: CameraPreview.sln

    msbuildArchitecture: x64

    configuration: '$(BuildConfiguration)'
